### ISSUE TITLE
Invalid parameter for API Versions > 31

### ISSUE THREAD

**Issue by vgrimaldi848** [jacklinquan/usb4a#6]
This should be changed from:

https://github.com/jacklinquan/usb4a/blob/c02980174ac37035996b2dceab42e69db178e995/usb4a/usb.py#L123

to:

` pintent = PendingIntent.getBroadcast(get_context(), 0, intent, PendingIntent.FLAG_IMMUTABLE)
`

to be working with more recent API versions.

**Comment by jacklinquan** [comment]
Hi, @vgrimaldi848 

Thank you for reporting this issue!
Could you help give more information on this issue:
What exception you came across? (better with the traceback information)

`PendingIntent.FLAG_IMMUTABLE` is introduced since API level 23 (Android 6).
Some API level testing condition needs to be added for backward compatibility for older Android devices.
I'll try to figure out a solution when I have time. Contributions are welcome too!

**Comment by jacklinquan** [comment]
Hi @vgrimaldi848 ,

This issue is solved with Version 0.3.0
Please try to upgrade `usb4a` package in your application to see if it works.
In case there's any further issue, please let me know.
Thank you very much!
